name: Handle new issue

on:
  issues:
    types: [opened,reopened]

jobs:
  handle_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v2
        with:
          comment: |
            Will not fix.
